name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch: # Allows manual run
  push: {branches: ["master", "main"]} 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: simonwinther
          template: classic
          base: ""
          config_timezone: Europe/Copenhagen
          
          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: fullyear
          
          # Habits & Activity
          plugin_habits: yes
          plugin_habits_charts: yes
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_compact: yes
